# Generated by Django 2.0.3 on 2018-03-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioSecurity',
        ),
    ]
