# Generated by Django 2.0.3 on 2018-03-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Bank name (e.g. Brack,DutchBangla)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter branch name', max_length=200, verbose_name='Branch Name')),
                ('address', models.CharField(help_text='Enter branch address', max_length=200, verbose_name='Branch Address')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter File Name', max_length=200, verbose_name='File Name')),
                ('bill', models.CharField(help_text='Enter Bill Amount', max_length=200, verbose_name='Bill Amount')),
                ('account_no', models.CharField(help_text='Enter Account No', max_length=200, verbose_name='Account No')),
                ('file', models.FileField(default=False, help_text='Upload File', upload_to='')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Bank')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Branch')),
            ],
        ),
    ]
