# Generated by Django 2.0.3 on 2018-03-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180319_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='doc',
        ),
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.File'),
        ),
    ]
